### ISSUE TITLE
Can't login via QR code

### ISSUE THREAD

**Issue by sergius-msv** [pokearaujo/multidevice#4]
Can't login via QR code. Whatsapp not answering to registerPayload

**Comment by YcleptJohn** [comment]
Seems to have stopped working for me today too

**Comment by burstfreeze** [comment]
I think the issue is QR code length. It looks vastly different to what it was before and now is 546 base64 chars in size.

WhatsApp Web MD QR Code is 218 chars.

I have adapted the new version and b64 encoded version but this does not make a difference for that case.
https://github.com/burstfreeze/multidevice/commit/ea44436676c3c443e9eb0d249844377da2a13b90

**Comment by burstfreeze** [comment]
I have just checked out commit 1a4e57913e39f215eb5583babbad16eb691b3e16 and it shows the normal QR code. I suppose poke messed up the QR code generation in the latest commit and did not notice because `storage.json` may remain valid after scanning QR code with the old commit, then logging in with the new commit.

If I had to take a wild guess I'd say it's the hkdf/expand/salting that changed with the most recent commit but poke will probably quicker to call it out 😅

**Comment by YcleptJohn** [comment]
Ooh interesting.. yeah it absolutely makes sense to be able to miss it if you're keeping the same storage.json around.. it does become forgettable. 

Thanks for exploring a bit more, if I end up spotting anything between those commits that fixes it I'll see if I can chuck open a PR on it.. but like you, Poke would definitely beat me to it if he's looking haha.

**Comment by burstfreeze** [comment]
Fixed https://github.com/pokearaujo/multidevice/pull/5

**Comment by YcleptJohn** [comment]
Lovely and simple revert haha, cheers ❤️

**Comment by burstfreeze** [comment]
https://github.com/pokearaujo/multidevice/pull/7 , a more clean PR, has been merged into master.

@sergius-msv please close the issue since it's fixed.

**Comment by sergius-msv** [comment]
@burstfreeze, thanks, issue fixed, just checked, works perfect now!
